# Generated by Django 4.2.4 on 2023-12-06 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "result_id",
                    models.CharField(help_text="Identifier for the result.", max_length=64, verbose_name="Identifier"),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="Sequence")),
                (
                    "size",
                    models.PositiveIntegerField(
                        blank=True, default=0, help_text="Size of the result in bytes.", null=True, verbose_name="Size"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="MIME type of the result.",
                        max_length=64,
                        null=True,
                        verbose_name="Mime Type",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="service.job",
                        verbose_name="Job",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["job", "sequence"], name="by_sequence"),
                    models.Index(fields=["job", "result_id"], name="by_result_id"),
                ],
                "unique_together": {("job", "result_id"), ("job", "sequence")},
            },
        ),
    ]
