# Generated by GitHub Copilot CLI on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_jobresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobresult",
            name="file_path",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Filesystem path for the persisted result artifact.",
                null=True,
                verbose_name="File Path",
            ),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="url",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Relative or absolute URL where the result can be retrieved.",
                max_length=255,
                null=True,
                verbose_name="URL",
            ),
        ),
    ]
