# Generated by Django 4.2.4 on 2026-06-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_jobresult_storage_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveSmallIntegerField()),
                ("survey_id", models.CharField(max_length=64)),
                ("stencil", models.JSONField()),
                ("stencil_type", models.CharField(max_length=16)),
                ("band", models.CharField(max_length=8)),
                ("output_format", models.CharField(max_length=16)),
                ("engine", models.CharField(max_length=32)),
                ("color", models.BooleanField(default=False)),
                ("rgb_bands", models.CharField(default="gri", max_length=16)),
                ("persist", models.BooleanField(default=False)),
                ("output_path", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EXECUTING", "Executing"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, default=None, null=True)),
                ("end_time", models.DateTimeField(blank=True, default=None, null=True)),
                ("error_message", models.TextField(blank=True, default=None, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="service.job"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["job", "sequence"], name="task_by_job"),
                    models.Index(fields=["job", "status"], name="task_by_job_status"),
                ],
                "unique_together": {("job", "sequence")},
            },
        ),
    ]
