# Generated by Django 4.2.4 on 2026-08-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0005_job_owner_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Browser session that owns an anonymous job. Never treat owner=NULL alone as public access.",
                max_length=40,
                null=True,
                verbose_name="Session key",
            ),
        ),
    ]
